INSERT INTO cursos (titulo, profesor, dia, turno, activo) VALUES
('Matemática I', 'Laura Gómez', 'LUNES', 'MAÑANA', TRUE),
('Historia Universal', 'Carlos Ruiz', 'MARTES', 'TARDE', TRUE),
('Física I', 'Ana Torres', 'MIERCOLES', 'NOCHE', TRUE),
('Programación I', 'Jorge Díaz', 'JUEVES', 'MAÑANA', TRUE),
('Química General', 'Sofía Romero', 'VIERNES', 'TARDE', TRUE),
('Literatura', 'María Fernández', 'LUNES', 'NOCHE', TRUE),
('Biología', 'José Pérez', 'MARTES', 'MAÑANA', TRUE),
('Geografía', 'Lucía Castro', 'MIERCOLES', 'TARDE', TRUE),
('Educación Cívica', 'Pedro López', 'JUEVES', 'NOCHE', TRUE),
('Arte Contemporáneo', 'Valeria Ortiz', 'VIERNES', 'MAÑANA', TRUE),
('Sociología', 'Martín García', 'LUNES', 'TARDE', TRUE),
('Economía', 'Carolina Díaz', 'MARTES', 'NOCHE', TRUE),
('Filosofía', 'Ricardo Benítez', 'MIERCOLES', 'MAÑANA', TRUE),
('Programación II', 'Jorge Díaz', 'JUEVES', 'TARDE', TRUE),
('Matemática II', 'Laura Gómez', 'VIERNES', 'NOCHE', TRUE),
('Historia Argentina', 'Carlos Ruiz', 'LUNES', 'MAÑANA', TRUE),
('Física II', 'Ana Torres', 'MARTES', 'TARDE', TRUE),
('Química Orgánica', 'Sofía Romero', 'MIERCOLES', 'NOCHE', TRUE),
('Inglés Técnico', 'Marina Herrera', 'JUEVES', 'MAÑANA', TRUE),
('Educación Física', 'Hernán Silva', 'VIERNES', 'TARDE', TRUE),
('Programación Web', 'Jorge Díaz', 'LUNES', 'NOCHE', TRUE),
('Estadística', 'Laura Gómez', 'MARTES', 'MAÑANA', TRUE),
('Redes y Comunicaciones', 'Hernán Silva', 'MIERCOLES', 'TARDE', TRUE),
('Derecho Laboral', 'Patricia Navarro', 'JUEVES', 'NOCHE', TRUE),
('Contabilidad', 'Carolina Díaz', 'VIERNES', 'MAÑANA', TRUE),
('Psicología', 'Ricardo Benítez', 'LUNES', 'TARDE', TRUE),
('Introducción a la Informática', 'Jorge Díaz', 'MARTES', 'NOCHE', TRUE),
('Marketing', 'Valeria Ortiz', 'MIERCOLES', 'MAÑANA', TRUE),
('Diseño Gráfico', 'Lucía Castro', 'JUEVES', 'TARDE', TRUE),
('Ética Profesional', 'Patricia Navarro', 'VIERNES', 'NOCHE', TRUE);

INSERT INTO alumnos (nombre, apellido, edad, id_curso, activo) VALUES
('Juan', 'Pérez', 20, 1, TRUE),
('Marcela', 'Díaz', 22, 2, TRUE),
('Lucas', 'Díaz', 19, 3, TRUE),
('Sofía', 'Romero', 25, 4, TRUE),
('Martín', 'López', 21, 5, TRUE),
('Carla', 'Fernández', 23, 6, TRUE),
('Diego', 'Ruiz', 28, 7, TRUE),
('Camila', 'Castro', 19, 8, TRUE),
('Nicolás', 'Benítez', 26, 9, TRUE),
('Lucía', 'Torres', 24, 10, TRUE),
('Agustín', 'Ortiz', 27, 11, TRUE),
('Valentina', 'Navarro', 20, 12, TRUE),
('Tomás', 'Silva', 22, 13, TRUE),
('Julieta', 'Herrera', 25, 14, TRUE),
('Ezequiel', 'García', 30, 15, TRUE),
('Paula', 'Morales', 19, 16, TRUE),
('Matías', 'Sánchez', 21, 17, TRUE),
('Florencia', 'Vega', 29, 18, TRUE),
('Joaquín', 'Martínez', 23, 19, TRUE),
('Antonella', 'Cáceres', 28, 20, TRUE),
('Pablo', 'Alonso', 24, 21, TRUE),
('Micaela', 'Bustamante', 22, 22, TRUE),
('Rodrigo', 'Gutiérrez', 31, 23, TRUE),
('Candela', 'Aguilar', 20, 24, TRUE),
('Gonzalo', 'Correa', 26, 25, TRUE),
('Milagros', 'Peralta', 19, 26, TRUE),
('Leandro', 'Carrizo', 27, 27, TRUE),
('Ailén', 'Mendoza', 23, 28, TRUE),
('Franco', 'Domínguez', 25, 29, TRUE),
('Bianca', 'Luna', 21, 30, TRUE);
